# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/mumba-motcamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/mumba-motcamera

PRODUCT_COPY_FILES += \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/MotoDesktopAppConfig/com.motorola.camera5.desktop-config.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/MotoDesktopAppConfig/com.motorola.camera5.desktop-config.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/init/init.motcamera5.lens.rc:$(TARGET_COPY_OUT_PRODUCT)/etc/init/init.motcamera5.lens.rc \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/permissions/com.motorola.camera5.adobe_scan.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera5.adobe_scan.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/permissions/com.motorola.camera5.lens.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera5.lens.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/permissions/com.motorola.camera5.mumba.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera5.mumba.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/permissions/com.motorola.camera5.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera5.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/permissions/com.motorola.moto-uirefresh.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.moto-uirefresh.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/permissions/deviceowner-configuration-com.motorola.camera5.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/deviceowner-configuration-com.motorola.camera5.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/permissions/privapp-permissions-com.motorola.camera5.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.motorola.camera5.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/sysconfig/hiddenapi-whitelist-com.motorola.camera5.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/hiddenapi-whitelist-com.motorola.camera5.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/etc/sysconfig/initial-package-stopped-states-com.motorola.camera5.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/initial-package-stopped-states-com.motorola.camera5.xml \
    vendor/motorola/mumba-motcamera/proprietary/product/media/audio/ui/camera_click.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/camera_click.ogg \
    vendor/motorola/mumba-motcamera/proprietary/product/media/audio/ui/camera_focus.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ui/camera_focus.ogg \
    vendor/motorola/mumba-motcamera/proprietary/system/etc/permissions/com.motorola.motosignature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.motosignature.xml \
    vendor/motorola/mumba-motcamera/proprietary/system/etc/permissions/moto-checkin.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-checkin.xml \
    vendor/motorola/mumba-motcamera/proprietary/system/etc/permissions/moto-core_services.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-core_services.xml \
    vendor/motorola/mumba-motcamera/proprietary/system/etc/permissions/moto-settings.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-settings.xml \
    vendor/motorola/mumba-motcamera/proprietary/system_ext/etc/public.libraries-moto.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/public.libraries-moto.txt \
    vendor/motorola/mumba-motcamera/proprietary/vendor/etc/permissions/com.motorola.camera.extensions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.camera.extensions.xml

PRODUCT_PACKAGES += \
    libenginepostproc.moto \
    MotoSignatureApp \
    MotCamera5 \
    MotorolaSettingsProvider \
    com.motorola.motosignature \
    moto-checkin \
    moto-core_services \
    moto-settings \
    com.motorola.camera.extensions \
    motsettings
